# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  name: 'uat-emr-com-sg-01'
  agent: 'uat-machine2'

steps:
- script: npm install
  displayName: 'npm install'
- script: copy "config\config.uat.js" "config\config.js" /Y
  displayName: 'update config to uat settings'
- script: 
    #export NODE_OPTIONS="--no-warnings --max-old-space-size=2048" && npm run build
    set NODE_OPTIONS=--max_old_space_size=8192 & npm run build
  displayName: 'npm build'
- task: CopyFiles@2
  inputs:
    SourceFolder: '.\dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'