export const menuData = [
  {
    title: 'Admin',
    text: 'Session Summary Report',
    url: '/report/sessionsummary',
    authority: 'report.admin.sessionsummary',
  },
  {
    title: 'Admin',
    text: 'Patient Listing Report',
    url: '/report/patientlisting',
    authority: 'report.finance.patientlisting',
  },
  {
    title: 'Finance',
    text: 'Payment Collection Report',
    url: '/report/paymentcollection',
    authority: 'report.finance.paymentcollection',
  },
  {
    title: 'Finance',
    text: 'GST Report',
    url: '/report/gstreport',
    authority: 'report.finance.gst',
  },
  {
    title: 'Finance',
    text: 'Queue Listing Report',
    url: '/report/queuelisting',
    authority: 'report.finance.queuelisting',
  },
  {
    title: 'Finance',
    text: 'Sales Listing Report',
    url: '/report/saleslistingreport',
    authority: 'report.finance.saleslisting',
  },
  {
    title: 'Finance',
    text: 'Sale Summary Report',
    url: '/report/salesummary',
    authority: 'report.finance.salessummary',
  },
  {
    title: 'Finance',
    text: 'Credit Note Listing Report',
    url: '/report/creditnotelistingreport',
    authority: 'report.finance.creditnotelisting',
  },
  {
    title: 'Finance',
    text: 'Void Credit Note & Payment Report',
    url: '/report/voidcreditnotereport',
    authority: 'report.finance.voidcreditnoteandpayment',
  },
  {
    title: 'Finance',
    text: 'Deposit Transaction Report',
    url: '/report/deposittransactionreport',
    authority: 'report.finance.deposittransaction',
  },
  {
    title: 'Finance',
    text: 'Outstanding Payment Report',
    url: '/report/outstandingpaymentreport',
    authority: 'report.finance.outstandingpayment',
  },
  {
    title: 'Finance',
    text: 'CHAS Claim Report',
    url: '/report/chasclaimreport',
    authority: 'report.finance.chasclaim',
  },
  {
    title: 'Inventory',
    text: 'Medication Movement Report',
    url: '/report/medicationmovementreport',
    authority: 'report.inventory.medicationmovement',
  },
  {
    title: 'Inventory',
    text: 'Consumable Movement Report',
    url: '/report/consumablemovementreport',
    authority: 'report.inventory.consumablemovement',
  },
  {
    title: 'Inventory',
    text: 'Low Stock Medication Report',
    url: '/report/lowstockmedicationreport',
    authority: 'report.inventory.lowstockmedication',
  },
  {
    title: 'Inventory',
    text: 'Low Stock Consumables Report',
    url: '/report/lowstockconsumablesreport',
    authority: 'report.inventory.lowstockconsumables',
  },
  {
    title: 'Inventory',
    text: 'Inventory Trending Report',
    url: '/report/inventorytrendingreport',
    authority: 'report.inventory.inventorytrendingreport',
  },
  {
    title: 'Inventory',
    text: 'Inventory Listing Report',
    url: '/report/inventorylistingreport',
    authority: 'report.inventory.inventorylistingreport',
  },
  {
    title: 'Other',
    text: 'Diagnosis Trending Report',
    url: '/report/diagnosistrending',
    authority: 'report.diagnosistrendingreport',
  },
]
