export const menuData = [
         {
           title: 'Admin',
           text: 'Session Summary Report',
           url: '/report/sessionsummary',
           authority: 'report.admin.sessionsummary',
         },
         {
           title: 'Admin',
           text: 'Patient Listing Report',
           url: '/report/patientlisting',
           authority: 'report.finance.patientlisting',
         },
         {
           title: 'Admin',
           text: 'Visit Listing Report',
           url: '/report/visitlistingreport',
           authority: 'report.admin.visitlistingreport',
         },
         {
           title: 'Finance',
           text: 'Payment Collection Report',
           url: '/report/paymentcollection',
           authority: 'report.finance.paymentcollection',
         },
         {
           title: 'Finance',
           text: 'GST Report',
           url: '/report/gstreport',
           authority: 'report.finance.gst',
         },
         {
           title: 'Finance',
           text: 'Queue Listing Report',
           url: '/report/queuelisting',
           authority: 'report.finance.queuelisting',
         },
         {
           title: 'Finance',
           text: 'Sales Listing Report',
           url: '/report/saleslistingreport',
           authority: 'report.finance.saleslisting',
         },
         {
           title: 'Finance',
           text: 'Sales Summary Report',
           url: '/report/salesummary',
           authority: 'report.finance.salessummary',
         },
         {
           title: 'Finance',
           text: 'Credit Note Listing Report',
           url: '/report/creditnotelistingreport',
           authority: 'report.finance.creditnotelisting',
         },
         {
           title: 'Finance',
           text: 'Void Credit Note & Payment Report',
           url: '/report/voidcreditnotereport',
           authority: 'report.finance.voidcreditnoteandpayment',
         },
         {
           title: 'Finance',
           text: 'Deposit Transaction Report',
           url: '/report/deposittransactionreport',
           authority: 'report.finance.deposittransaction',
         },
         {
           title: 'Finance',
           text: 'Outstanding Payment Report',
           url: '/report/outstandingpaymentreport',
           authority: 'report.finance.outstandingpayment',
         },
         {
           title: 'Finance',
           text: 'Invoice Listing Report',
           url: '/report/invoicelistingreport',
           authority: 'report.finance.invoicelisting',
         },
         {
           title: 'Finance',
           text: 'Statement Summary Report',
           url: '/report/statementsummaryreport',
           authority: 'report.finance.statementsummaryreport',
         },
         {
           title: 'Finance',
           text: 'Payment Collection Report (Summary)',
           url: '/report/paymentcollectionsummary',
           authority: 'report.finance.paymentcollectionsummary',
         },
         {
           title: 'Finance',
           text: 'Patient Ageing Report',
           url: '/report/patientageingreport',
           authority: 'report.finance.patientageingreport',
         },
         {
           title: 'Finance',
           text: 'Radiology Statistic Report',
           url: '/report/radiologystatisticreport',
           authority: 'report.finance.radiologystatisticreport',
         },
         {
           title: 'Finance',
           text: 'Xero Invoices Report',
           url: '/report/xeroinvoicesreport',
           authority: 'report.finance.xeroinvoicesreport',
         },
         {
           title: 'Inventory',
           text: 'Inventory Movement Report',
           url: '/report/inventorymovementreport',
           authority: 'report.inventory.inventorymovement',
         },
         {
           title: 'Inventory',
           text: 'Inventory Threshold Report',
           url: '/report/lowstockreport',
           authority: 'report.inventory.lowstock',
         },
         {
           title: 'Inventory',
           text: 'Inventory Trending Report',
           url: '/report/inventorytrendingreport',
           authority: 'report.inventory.inventorytrendingreport',
         },
         {
           title: 'Inventory',
           text: 'Inventory Listing Report',
           url: '/report/inventorylistingreport',
           authority: 'report.inventory.inventorylistingreport',
         },
         {
           title: 'Inventory',
           text: 'Inventory Stock Count Report',
           url: '/report/inventorystockcountreport',
           authority: 'report.inventory.inventorystockcountreport',
         },
         {
           title: 'Inventory',
           text: 'Purchase & Receiving Report',
           url: '/report/purchasereceivinglistingreport',
           authority: 'report.inventory.purchasereceivinglistingreport',
         },
         {
           title: 'Inventory',
           text: 'Expiring Stock Report',
           url: '/report/expiringstockreport',
           authority: 'report.inventory.expiringstockreport',
         },

         {
           title: 'Inventory',
           text: 'Dispensary Report',
           url: '/report/dispensaryreport',
           authority: 'report.inventory.partialdispensereport',
         },
         {
           title: 'Other',
           text: 'Diagnosis Trending Report',
           url: '/report/diagnosistrending',
           authority: 'report.other.diagnosistrending',
         },
         {
           title: 'Other',
           text: 'Referral Source Report ',
           url: '/report/referralsourcereport',
           authority: 'report.other.referralsource',
         },
         {
           title: 'Finance',
           text: 'WIP Revenue Report',
           url: '/report/wiprevenue',
           authority: 'report.finance.wiprevenuereport',
         },
         {
           title: 'Finance',
           text: 'Sales Listing By Performer Report',
           url: '/report/saleslistingbyperformer',
           authority: 'report.finance.saleslistingbyperformerreport',
         },
         {
           title: 'Finance',
           text: 'Package Expiry Report',
           url: '/report/packageexpiry',
           authority: 'report.finance.packageexpiryreport',
         },
       ]
