export const fakeInvoiceDetailData = {
  patientName: 'Lee Tian Kang',
  patientAccountNo: 'A4696976F',
  invoiceNo: 'IV-A0001',
  invoiceDate: '2019-09-17T07:47:18.511Z',
  invoiceTotal: 5000,
  totalAdjustment: 109.99,
  invoiceGSTAmt: 50.99,
  invoiceTotalAftGST: 5160.98,
  totalCreditNoteAmt: 1000,
  outstandingBalance: 2500,
  writeOffAmount: 200,
  totalPayment: 888,
  remark: 'This is invoice remarks.',
  invoiceItem: [
    {
      itemType: 'Medication',
      itemName: 'Panadol',
      quantity: 1,
      adjAmt: 3,
      totalAfterItemAdjustment: 1097,
      id: 1,
      isDeleted: false,
      // concurrencyToken: 0,
    },
    {
      itemType: 'Vaccination',
      itemName: 'Chicken Pox Vaccine',
      quantity: 1,
      adjAmt: 0,
      totalAfterItemAdjustment: 8,
      id: 2,
      isDeleted: false,
      // concurrencyToken: 0,
    },
    {
      itemType: 'Service',
      itemName: 'Consulation Service	',
      quantity: 1,
      adjAmt: 0,
      totalAfterItemAdjustment: 1,
      id: 3,
      isDeleted: false,
      // concurrencyToken: 0,
    },
  ],
  invoiceAdjustment: [
    // {
    //   adjRemark: 'Adjust 109',
    //   adjAmount: 109,
    //   sequence: 1,
    //   id: 1,
    //   isDeleted: false,
    //   //concurrencyToken: 0,
    // },
    // {
    //   adjRemark: 'Second Adjust',
    //   adjAmount: 91,
    //   sequence: 2,
    //   id: 2,
    //   isDeleted: false,
    //   //concurrencyToken: 0,
    // },
  ],
  id: 0,
  isDeleted: false,
  // concurrencyToken: 0,
}

export const fakeInvoicePaymentData = {
  patientProfileFK: 1,
  invoiceFK: 1,
  payerTypeFK: 0,
  companyFK: 0,
  schemePayerFK: 0,
  coPaymentSchemeFK: 0,
  sequence: 0,
  payerDistributedAmt: 0,
  isCancelled: false,
  cancelDate: '2019-09-19T01:29:50.836Z',
  cancelReason: 'string',
  cancelByUserFK: 0,
  patientName: 'string',
  companyName: 'string',
  payerType: 'string',
  invoicePayment: [
    {
      invoicePayerFK: 1,
      receiptNo: 'RC/000001',
      totalAmtPaid: 2500,
      cashReceived: 0,
      cashReturned: 0,
      paymentReceivedDate: '2019-09-19T01:29:50.836Z',
      paymentReceivedByUserFK: 0,
      paymentReceivedBizSessionFK: 0,
      paymentCreatedBizSessionFK: 0,
      isCancelled: false,
      cancelDate: '2019-09-19T01:29:50.836Z',
      cancelReason: 'string',
      cancelByUserFK: 0,
      invoicePaymentMode: [
        {
          paymentFK: 0,
          paymentModeFK: 0,
          paymentMode: 'string',
          amt: 0,
          cashRounding: 0,
          sequence: 0,
          remark: 'string',
          giroPayment: [
            {
              paymentModeFK: 0,
              refNo: 'string',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          chequePayment: [
            {
              paymentModeFK: 0,
              chequeNo: 'string',
              collectionDate: '2019-09-19T01:29:50.836Z',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          creditCardPayment: [
            {
              paymentModeFK: 0,
              creditCardNo: 'string',
              creditCardTypeFK: 0,
              creditCardType: 'string',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          netsPayment: [
            {
              paymentModeFK: 0,
              refNo: 'string',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          depositPayment: [
            {
              paymentModeFK: 0,
              depositAccountFK: 0,
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          id: 0,
          isDeleted: false,
          concurrencyToken: 0,
        },
      ],
      id: 5,
      isDeleted: false,
      concurrencyToken: 0,
    },
    {
      invoicePayerFK: 1,
      receiptNo: 'RC/000002',
      totalAmtPaid: 1500,
      cashReceived: 0,
      cashReturned: 0,
      paymentReceivedDate: '2019-09-19T01:29:50.836Z',
      paymentReceivedByUserFK: 0,
      paymentReceivedBizSessionFK: 0,
      paymentCreatedBizSessionFK: 0,
      isCancelled: false,
      cancelDate: '2019-09-19T01:29:50.836Z',
      cancelReason: 'string',
      cancelByUserFK: 0,
      invoicePaymentMode: [
        {
          paymentFK: 0,
          paymentModeFK: 0,
          paymentMode: 'string',
          amt: 0,
          cashRounding: 0,
          sequence: 0,
          remark: 'string',
          giroPayment: [
            {
              paymentModeFK: 0,
              refNo: 'string',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          chequePayment: [
            {
              paymentModeFK: 0,
              chequeNo: 'string',
              collectionDate: '2019-09-19T01:27:50.836Z',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          creditCardPayment: [
            {
              paymentModeFK: 0,
              creditCardNo: 'string',
              creditCardTypeFK: 0,
              creditCardType: 'string',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          netsPayment: [
            {
              paymentModeFK: 0,
              refNo: 'string',
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          depositPayment: [
            {
              paymentModeFK: 0,
              depositAccountFK: 0,
              id: 0,
              isDeleted: false,
              concurrencyToken: 0,
            },
          ],
          id: 0,
          isDeleted: false,
          concurrencyToken: 0,
        },
      ],
      id: 4,
      isDeleted: false,
      concurrencyToken: 0,
    },
    // {
    //   invoicePayerFK: 2,
    //   receiptNo: 'RC/000002',
    //   totalAmtPaid: 700,
    //   cashReceived: 0,
    //   cashReturned: 0,
    //   paymentReceivedDate: '2019-09-19T01:29:50.836Z',
    //   paymentReceivedByUserFK: 0,
    //   paymentReceivedBizSessionFK: 0,
    //   paymentCreatedBizSessionFK: 0,
    //   isCancelled: false,
    //   cancelDate: '2019-09-19T01:29:50.836Z',
    //   cancelReason: 'string',
    //   cancelByUserFK: 0,
    //   invoicePaymentMode: [
    //     {
    //       paymentFK: 0,
    //       paymentModeFK: 0,
    //       paymentMode: 'string',
    //       amt: 0,
    //       cashRounding: 0,
    //       sequence: 0,
    //       remark: 'string',
    //       giroPayment: [
    //         {
    //           paymentModeFK: 0,
    //           refNo: 'string',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       chequePayment: [
    //         {
    //           paymentModeFK: 0,
    //           chequeNo: 'string',
    //           collectionDate: '2019-09-19T01:29:50.836Z',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       creditCardPayment: [
    //         {
    //           paymentModeFK: 0,
    //           creditCardNo: 'string',
    //           creditCardTypeFK: 0,
    //           creditCardType: 'string',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       netsPayment: [
    //         {
    //           paymentModeFK: 0,
    //           refNo: 'string',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       depositPayment: [
    //         {
    //           paymentModeFK: 0,
    //           depositAccountFK: 0,
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       id: 0,
    //       isDeleted: false,
    //       concurrencyToken: 0,
    //     },
    //   ],
    //   id: 0,
    //   isDeleted: false,
    //   concurrencyToken: 0,
    // },
    // {
    //   invoicePayerFK: 3,
    //   receiptNo: 'RC/000003',
    //   totalAmtPaid: 800,
    //   cashReceived: 0,
    //   cashReturned: 0,
    //   paymentReceivedDate: '2019-09-19T01:29:50.836Z',
    //   paymentReceivedByUserFK: 0,
    //   paymentReceivedBizSessionFK: 0,
    //   paymentCreatedBizSessionFK: 0,
    //   isCancelled: false,
    //   cancelDate: '2019-09-19T01:29:50.836Z',
    //   cancelReason: 'string',
    //   cancelByUserFK: 0,
    //   invoicePaymentMode: [
    //     {
    //       paymentFK: 0,
    //       paymentModeFK: 0,
    //       paymentMode: 'string',
    //       amt: 0,
    //       cashRounding: 0,
    //       sequence: 0,
    //       remark: 'string',
    //       giroPayment: [
    //         {
    //           paymentModeFK: 0,
    //           refNo: 'string',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       chequePayment: [
    //         {
    //           paymentModeFK: 0,
    //           chequeNo: 'string',
    //           collectionDate: '2019-09-19T01:29:50.836Z',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       creditCardPayment: [
    //         {
    //           paymentModeFK: 0,
    //           creditCardNo: 'string',
    //           creditCardTypeFK: 0,
    //           creditCardType: 'string',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       netsPayment: [
    //         {
    //           paymentModeFK: 0,
    //           refNo: 'string',
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       depositPayment: [
    //         {
    //           paymentModeFK: 0,
    //           depositAccountFK: 0,
    //           id: 0,
    //           isDeleted: false,
    //           concurrencyToken: 0,
    //         },
    //       ],
    //       id: 0,
    //       isDeleted: false,
    //       concurrencyToken: 0,
    //     },
    //   ],
    //   id: 0,
    //   isDeleted: false,
    //   concurrencyToken: 0,
    // },
  ],
  creditNote: [
    {
      invoicePayerFK: 1,
      creditNoteNo: 'CN/000001',
      remark: 'Credit note reason here.',
      generatedDate: '2019-09-19T01:40:50.836Z',
      generatedByUserFK: 0,
      total: 0,
      isGSTInclusive: false,
      gstValue: 0,
      gstAmt: 0,
      totalAftGST: 139,
      isStockIn: false,
      isCancelled: true,
      cancelDate: '2019-09-19T01:29:50.836Z',
      cancelReason: 'This credit note is void.',
      cancelByUserFK: 0,
      creditNoteItem: [],
      id: 7,
      isDeleted: false,
      concurrencyToken: 0,
    },
    {
      invoicePayerFK: 1,
      creditNoteNo: 'CN/000002',
      remark: 'Credit note remarks here.',
      generatedDate: '2019-09-19T01:40:50.836Z',
      generatedByUserFK: 0,
      total: 0,
      isGSTInclusive: false,
      gstValue: 0,
      gstAmt: 0,
      totalAftGST: 600,
      isStockIn: false,
      isCancelled: false,
      cancelDate: '2019-09-19T01:29:50.836Z',
      cancelReason: 'string',
      cancelByUserFK: 0,
      creditNoteItem: [
        {
          creditNoteFK: 1,
          itemTypeFK: 88,
          invoiceItemFK: 99,
          stockTransactionFK: 0,
          itemCode: 'IC/000001',
          itemDescription: 'Item description here',
          isInventoryItem: false,
          isPackage: false,
          costPrice: 109,
          unitPrice: 109,
          quantity: 1,
          subTotal: 109,
          id: 1,
          isDeleted: false,
          concurrencyToken: 0,
        },
        {
          creditNoteFK: 1,
          itemTypeFK: 101,
          invoiceItemFK: 201,
          stockTransactionFK: 0,
          itemCode: 'IC/000002',
          itemDescription: 'Item description here',
          isInventoryItem: false,
          isPackage: false,
          costPrice: 139,
          unitPrice: 139,
          quantity: 1,
          subTotal: 139,
          id: 2,
          isDeleted: false,
          concurrencyToken: 0,
        },
      ],
      id: 8,
      isDeleted: false,
      concurrencyToken: 0,
    },
  ],
  invoicePayerWriteOff: [
    {
      invoicePayerFK: 1,
      writeOffCode: 'WO/000001',
      writeOffDate: '2019-09-19T01:29:50.836Z',
      writeOffAmount: 900,
      writeOffReason: 'Write off reason here.',
      isCancelled: true,
      cancelDate: '2019-09-19T01:29:50.836Z',
      cancelReason: 'This write off is void.',
      cancelByUserFK: 0,
      id: 3,
      isDeleted: false,
      concurrencyToken: 0,
    },
    {
      invoicePayerFK: 1,
      writeOffCode: 'WO/000001',
      writeOffDate: '2019-09-19T01:29:50.836Z',
      writeOffAmount: 100,
      writeOffReason: 'Write off reason here.',
      isCancelled: false,
      cancelDate: '2019-09-19T01:29:50.836Z',
      cancelReason: 'This write off is void.',
      cancelByUserFK: 0,
      id: 11,
      isDeleted: false,
      concurrencyToken: 0,
    },
  ],
  id: 99,
  isDeleted: false,
  concurrencyToken: 0,
}
