export default {
  'visit.queueNo': 'queueNo',
  'visit.visitType': 'visitPurposeFK',
  'visit.salesType': 'salesTypeFK',
  'visit.doctorProfileFk': 'doctorProfileFK',
  'visit.isDoctorInCharge': 'isDoctorInCharge',
  'visit.visitRemarks': 'visitRemarks',
  'visit.roomFK': 'roomFK',
  'visit.visitOrderTemplateFK': 'visitOrderTemplateFK',
  'visit.VisitOrderTemplateTotal': 'visitOrderTemplateTotal',
  'visit.salesPersonUserFK': 'salesPersonUserFK',
  'visit.consReady': 'consReady',

  'vitalsign.temperatureC': 'temperatureC',
  'vitalsign.bpSysMMHG': 'bpSysMMHG',
  'vitalsign.bpDiaMMHG': 'bpDiaMMHG',
  'vitalsign.pulseRateBPM': 'pulseRateBPM',
  'vitalsign.saO2': 'saO2',
  'vitalsign.weightKG': 'weightKG',
  'vitalsign.heightCM': 'heightCM',
  'vitalsign.bmi': 'bmi',
  'vitalsign.bodyFatPercentage': 'bodyFatPercentage',
  'vitalsign.degreeOfObesity': 'degreeOfObesity',
  'vitalsign.headCircumference': 'headCircumference',
  'vitalsign.chestCircumference': 'chestCircumference',
  'vitalsign.waistCircumference': 'waistCircumference',
  'vitalsign.isChild': 'isChild',
  'vitalsign.isPregnancy': 'isPregnancy',
  'vitalsign.hepetitisVaccinationA': 'hepetitisVaccinationA',
  'vitalsign.hepetitisVaccinationB': 'hepetitisVaccinationB',
  'vitalsign.isFasting': 'isFasting',
  'vitalsign.isSmoking': 'isSmoking',
  'vitalsign.isAlcohol': 'isAlcohol',
  'vitalsign.isMensus': 'isMensus',

  'participant.participant': 'participant',
  'participant.participants': 'participants',
}
