module.exports = [
  {
    id: 1,
    icon: 'laptop',
    name: 'Dashboard',
    router: '/dashboard',
  },
  {
    id: 2,
    breadParentId: 1,
    name: 'Users',
    icon: 'user',
    router: '/user',
  },
  {
    id: 7,
    breadParentId: 1,
    name: 'Posts',
    icon: 'shopping-cart',
    router: '/post',
  },
  {
    id: 21,
    menuParentId: -1,
    breadParentId: 2,
    name: 'User Detail',
    router: '/user/:id',
  },
  {
    id: 3,
    breadParentId: 1,
    name: 'Request',
    icon: 'api',
    router: '/request',
  },
  {
    id: 4,
    breadParentId: 1,
    name: 'UI Element',
    icon: 'camera-o',
  },
  {
    id: 41,
    breadParentId: 4,
    menuParentId: 4,
    name: 'IconFont',
    icon: 'heart-o',
    router: '/UIElement/iconfont',
  },
  {
    id: 42,
    breadParentId: 4,
    menuParentId: 4,
    name: 'DataTable',
    icon: 'database',
    router: '/UIElement/dataTable',
  },
  {
    id: 43,
    breadParentId: 4,
    menuParentId: 4,
    name: 'DropOption',
    icon: 'bars',
    router: '/UIElement/dropOption',
  },
  {
    id: 44,
    breadParentId: 4,
    menuParentId: 4,
    name: 'Search',
    icon: 'search',
    router: '/UIElement/search',
  },
  {
    id: 45,
    breadParentId: 4,
    menuParentId: 4,
    name: 'Editor',
    icon: 'edit',
    router: '/UIElement/editor',
  },
  {
    id: 46,
    breadParentId: 4,
    menuParentId: 4,
    name: 'layer (Function)',
    icon: 'credit-card',
    router: '/UIElement/layer',
  },
  {
    id: 5,
    breadParentId: 1,
    name: 'Recharts',
    icon: 'code-o',
  },
  {
    id: 51,
    breadParentId: 5,
    menuParentId: 5,
    name: 'LineChart',
    icon: 'line-chart',
    router: '/chart/lineChart',
  },
  {
    id: 52,
    breadParentId: 5,
    menuParentId: 5,
    name: 'BarChart',
    icon: 'bar-chart',
    router: '/chart/barChart',
  },
  {
    id: 53,
    breadParentId: 5,
    menuParentId: 5,
    name: 'AreaChart',
    icon: 'area-chart',
    router: '/chart/areaChart',
  },
  {
    id: 6,
    breadParentId: 1,
    name: 'Test Navigation',
    icon: 'setting',
  },
  {
    id: 61,
    breadParentId: 6,
    menuParentId: 6,
    name: 'Test Navigation1',
    router: '/navigation/navigation1',
  },
  {
    id: 62,
    breadParentId: 6,
    menuParentId: 6,
    name: 'Test Navigation2',
    router: '/navigation/navigation2',
  },
  {
    id: 621,
    breadParentId: 62,
    menuParentId: 62,
    name: 'Test Navigation21',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 622,
    breadParentId: 62,
    menuParentId: 62,
    name: 'Test Navigation22',
    router: '/navigation/navigation2/navigation2',
  },
]
