const now = new Date()

export const dndEvents = [
  {
    id: 1,
    title: 'leong',
    start: new Date(2019, 5, 29, 23, 40, 0),
    end: new Date(2019, 5, 30, 13, 0, 0),
    startTime: '11:40 pm',
    endTime: '01:00 pm',
    resourceId: 'cheah',
    patientName: 'leong',
    contactNo: '12345678',
    appointmentType: 'consultation',
    color: 'cyan',
    doctor: 'cheah',
  },
  {
    id: 2,
    title: 'Ah Fatt',
    start: new Date(2019, 5, 29, 9, 0, 0),
    end: new Date(2019, 5, 29, 13, 0, 0),
    startTime: '09:00 am',
    endTime: '01:30 pm',
    resourceId: 'levinne',
    patientName: 'Ah Fatt',
    contactNo: '12345678',
    appointmentType: 'pillChecks',
    color: 'pink',
    doctor: 'levinne',
  },
  {
    id: 3,
    title: 'Lim',
    start: new Date(2019, 5, 30, 7, 0, 0),
    end: new Date(2019, 5, 30, 10, 30, 0),
    startTime: '07:00 am',
    endTime: '10:30 am',
    resourceId: 'tan',
    patientName: 'Lim',
    contactNo: '12345678',
    appointmentType: 'urgent',
    color: 'indigo',
    doctor: 'tan',
  },
  {
    id: 4,
    title: 'Loon',
    start: new Date(2019, 5, 30, 7, 0, 0),
    end: new Date(2019, 5, 30, 10, 30, 0),
    startTime: '07:00 am',
    endTime: '10:30 am',
    resourceId: 'medisys',
    patientName: 'Loon',
    contactNo: '12345678',
    appointmentType: 'urgent',
    color: 'indigo',
    doctor: 'medisys',
  },
  {
    id: 5,
    title: 'Seng',
    start: new Date(2019, 5, 30, 7, 0, 0),
    end: new Date(2019, 5, 30, 10, 30, 0),
    startTime: '07:00 am',
    endTime: '10:30 am',
    resourceId: 'cheah',
    patientName: 'Seng',
    contactNo: '12345678',
    appointmentType: 'urgent',
    color: 'indigo',
    doctor: 'cheah',
  },
  {
    id: 4,
    title: 'Annie',
    start: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 30, 0),
    end: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 15, 0),
    startTime: '08:30 am',
    endTime: '09:15 am',
    resourceId: 'medisys',
    patientName: 'Annie',
    contactNo: '12345678',
    appointmentType: 'checkup',
    color: 'red',
    doctor: 'medisys',
  },
  {
    id: 5,
    title: 'Ah Huat',
    start: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 0, 0),
    end: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 30, 0),
    startTime: '09:00 am',
    endTime: '09:30 am',
    resourceId: 'levinne',
    patientName: 'Ah Huat',
    contactNo: '11223344',
    appointmentType: 'aesthetic',
    color: 'green',
    doctor: 'levinne',
  },
  {
    id: 6,
    title: 'Point in Time Event',
    start: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 0, 0),
    end: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 9, 0, 0),
    startTime: '08:00 am',
    endTime: '09:00 am',
    resourceId: 'other',
    patientName: 'Ah Keow',
    contactNo: '22113344',
    appointmentType: 'dental',
    color: 'blue',
    doctor: '',
  },
  {
    id: 7,
    hasConflict: true,
    title: 'Ah Mao',
    start: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 30, 0),
    end: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 10, 0, 0),
    startTime: '08:30 am',
    endTime: '10:00 am',
    resourceId: 'cheah',
    patientName: 'Ah Mao',
    contactNo: '22113344',
    appointmentType: 'urgent',
    color: 'indigo',
    doctor: 'cheah',
  },
  {
    id: 8,
    hasConflict: true,
    title: 'This event has conflict in schedule',
    start: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 8, 0, 0),
    end: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 10, 0, 0),
    startTime: '08:00 am',
    endTime: '10:00 am',
    resourceId: 'cheah',
    patientName: 'Ah Keow',
    contactNo: '22113344',
    appointmentType: 'dental',
    color: 'blue',
    doctor: 'cheah',
  },
  {
    id: 9,
    hasConflict: false,
    start: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 11, 0, 0),
    end: new Date(now.getFullYear(), now.getMonth(), now.getDate(), 12, 0, 0),
    startTime: '11:00 am',
    endTime: '12:00 pm',
    resourceId: 'cheah',
    patientName: 'Ah Keow',
    contactNo: '22113344',
    appointmentType: 'pillChecks',
    color: 'pink',
    doctor: 'cheah',
  },
]

export default [
  {
    id: 0,
    title: 'All Day Event very long title',
    allDay: true,
    start: new Date(2019, 3, 0),
    end: new Date(2019, 3, 1),
  },
  {
    id: 1,
    title: 'Long Event',
    start: new Date(2019, 3, 7),
    end: new Date(2019, 3, 10),
  },

  {
    id: 2,
    title: 'DTS STARTS',
    start: new Date(2016, 2, 13, 0, 0, 0),
    end: new Date(2016, 2, 20, 0, 0, 0),
  },

  {
    id: 3,
    title: 'DTS ENDS',
    start: new Date(2016, 10, 6, 0, 0, 0),
    end: new Date(2016, 10, 13, 0, 0, 0),
  },

  {
    id: 4,
    title: 'Some Event',
    start: new Date(2019, 3, 9, 0, 0, 0),
    end: new Date(2019, 3, 10, 0, 0, 0),
  },
  {
    id: 5,
    title: 'Conference',
    start: new Date(2019, 6, 11),
    end: new Date(2019, 6, 13),
    desc: 'Big conference for important people',
  },
  {
    id: 6,
    title: 'Meeting',
    start: new Date(2019, 6, 12, 10, 30, 0, 0),
    end: new Date(2019, 6, 12, 12, 30, 0, 0),
    desc: 'Pre-meeting meeting, to prepare for the meeting',
  },
  {
    id: 7,
    title: 'Lunch',
    start: new Date(2019, 6, 12, 12, 0, 0, 0),
    end: new Date(2019, 6, 12, 13, 0, 0, 0),
    desc: 'Power lunch',
  },
  {
    id: 8,
    title: 'Meeting',
    start: new Date(2019, 6, 12, 14, 0, 0, 0),
    end: new Date(2019, 6, 12, 15, 0, 0, 0),
  },
  {
    id: 9,
    title: 'Happy Hour',
    start: new Date(2019, 6, 12, 17, 0, 0, 0),
    end: new Date(2019, 6, 12, 17, 30, 0, 0),
    desc: 'Most important meal of the day',
  },
  {
    id: 10,
    title: 'Dinner',
    start: new Date(2019, 6, 12, 20, 0, 0, 0),
    end: new Date(2019, 6, 12, 21, 0, 0, 0),
  },
  {
    id: 11,
    title: 'Birthday Party',
    start: new Date(2019, 6, 13, 7, 0, 0),
    end: new Date(2019, 6, 13, 10, 30, 0),
  },
  {
    id: 12,
    title: 'Late Night Event',
    start: new Date(2019, 6, 17, 19, 30, 0),
    end: new Date(2019, 6, 18, 2, 0, 0),
  },
  {
    id: 12.5,
    title: 'Late Same Night Event',
    start: new Date(2019, 6, 17, 19, 30, 0),
    end: new Date(2019, 6, 17, 23, 30, 0),
  },
  {
    id: 13,
    title: 'Multi-day Event',
    start: new Date(2019, 6, 20, 19, 30, 0),
    end: new Date(2019, 6, 22, 2, 0, 0),
  },
  {
    id: 14,
    title: 'Today',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() + 3)),
  },
  {
    id: 16,
    title: 'Today',
    start: new Date(new Date().setHours(new Date().getHours() - 3)),
    end: new Date(new Date().setHours(new Date().getHours() + 3)),
  },
  {
    id: 15,
    title: 'Point in Time Event',
    start: now,
    end: now,
  },
]
