export const Authority = {
  'Master Setting': 'settings.mastersetting',
  'Clinic Setting': 'settings.clinicsetting',
  'Print Setup': 'settings.printsetup',
  'System User': 'settings.systemuser',
  'User Preference': 'settings.userpreference',
  Templates: 'settings.template',
  Contact: 'settings.contact',
}

export const menuData = [
  {
    authority: 'settings.mastersetting.clinicinformation',
    title: 'Master Setting',
    text: 'Clinic Information',
    url: '/setting/clinicinfo',
  },
  {
    authority: 'settings.mastersetting.gstsetup',
    title: 'Master Setting',
    text: 'GST Setup',
    url: '/setting/gstsetup',
  },
  {
    authority: 'settings.mastersetting.generalsetting',
    title: 'Master Setting',
    text: 'General Setting',
    url: '/setting/generalsetting',
  },
  {
    authority: 'settings.mastersetting.queuedisplaysetup',
    title: 'Master Setting',
    text: 'Queue Display Setup',
    url: '/setting/queuedisplaysetup',
  },
  {
    authority: 'settings.clinicsetting.service',
    title: 'Clinic Setting',
    text: 'Service',
    url: '/setting/service',
  },
  {
    authority: 'settings.clinicsetting.servicecenter',
    title: 'Clinic Setting',
    text: 'Service Center',
    // icon: <Business />,
    url: '/setting/servicecenter',
  },
  {
    authority: 'settings.clinicsetting.servicecentercategory',
    title: 'Clinic Setting',
    text: 'Service Center Category',
    // icon: <FolderOpen />,
    url: '/setting/servicecentercategory',
  },
  {
    authority: 'settings.clinicsetting.servicecategory',
    title: 'Clinic Setting',
    text: 'Service Category',
    // icon: <FolderOpen />,
    url: '/setting/servicecategory',
  },
  {
    authority: 'settings.clinicsetting.revenuecategory',
    title: 'Clinic Setting',
    text: 'Revenue Category',
    // icon: <FolderOpen />,
    url: '/setting/revenuecategory',
  },
  {
    authority: 'settings.clinicsetting.room',
    title: 'Clinic Setting',
    text: 'Room',
    url: '/setting/room',
  },
  {
    authority: 'settings.clinicsetting.roomassignment',
    title: 'Clinic Setting',
    text: 'Room Assignment',
    url: '/setting/roomassignment',
  },
  {
    authority: 'settings.clinicsetting.clinicoperationhour',
    title: 'Clinic Setting',
    text: 'Clinic Operation Hour',
    url: '/setting/clinicoperationhour',
  },
  {
    authority: 'settings.clinicsetting.clinicbreakhour',
    title: 'Clinic Setting',
    text: 'Clinic Break Hour',
    url: '/setting/clinicbreakhour',
  },
  {
    authority: 'settings.clinicsetting.publicholiday',
    title: 'Clinic Setting',
    text: 'Public Holiday',
    url: '/setting/publicholiday',
  },
  {
    authority: 'settings.clinicsetting.doctorblock',
    title: 'Clinic Setting',
    text: 'Doctor Block',
    url: '/setting/doctorblock',
  },
  // {
  //   title: 'Clinic Setting',
  //   text: 'Participant Role',
  //   url: '/setting/participantrole',
  // },
  {
    authority: 'settings.clinicsetting.roomblock',
    title: 'Clinic Setting',
    text: 'Room Block',
    url: '/setting/roomblock',
  },
  {
    authority: 'settings.clinicsetting.medicationuom',
    title: 'Clinic Setting',
    text: 'Medication UOM',
    url: '/setting/medicationuom',
  },
  {
    authority: 'settings.clinicsetting.consumableuom',
    title: 'Clinic Setting',
    text: 'Consumable UOM',
    url: '/setting/consumableuom',
  },
  {
    authority: 'settings.clinicsetting.medicationgroup',
    title: 'Clinic Setting',
    text: 'Medication Group',
    url: '/setting/medicationgroup',
  },
  {
    authority: 'settings.clinicsetting.consumablecategory',
    title: 'Clinic Setting',
    text: 'Consumable Category',
    url: '/setting/consumablegroup',
  },
  {
    authority: 'settings.clinicsetting.medicationdosage',
    title: 'Clinic Setting',
    text: 'Medication Dosage',
    url: '/setting/medicationdosage',
  },
  {
    authority: 'settings.clinicsetting.medicationprecaution',
    title: 'Clinic Setting',
    text: 'Medication Precaution',
    url: '/setting/medicationprecautions',
  },
  {
    authority: 'settings.clinicsetting.medicationfrequency',
    title: 'Clinic Setting',
    text: 'Medication Frequency',
    url: '/setting/medicationfrequency',
  },
  {
    authority: 'settings.clinicsetting.medicationconsumptionmethod',
    title: 'Clinic Setting',
    text: 'Medication Consumption Method',
    longText: true,
    url: '/setting/medicationconsumptionmethod',
  },
  {
    authority: 'settings.clinicsetting.paymentmode',
    title: 'Clinic Setting',
    text: 'Payment Mode',
    url: '/setting/paymentmode',
  },
  {
    authority: 'settings.clinicsetting.appointmenttype',
    title: 'Clinic Setting',
    text: 'Appointment Type',
    url: '/setting/appointmenttype',
  },
  {
    authority: 'settings.clinicsetting.treatment',
    title: 'Clinic Setting',
    text: 'Treatment',
    // icon: <FolderOpen />,
    url: '/setting/treatment',
  },
  {
    authority: 'settings.clinicsetting.treatmentcategory',
    title: 'Clinic Setting',
    text: 'Treatment Category',
    // icon: <FolderOpen />,
    url: '/setting/treatmentcategory',
  },
  {
    authority: 'settings.clinicsetting.casetype',
    title: 'Clinic Setting',
    text: 'Case Type',
    url: '/setting/casetype',
  },
  {
    authority: 'settings.clinicsetting.casedescription',
    title: 'Clinic Setting',
    text: 'Case Description',
    url: '/setting/casedescription',
  },
  {
    authority: 'settings.clinicsetting.refractiontesttype',
    title: 'Clinic Setting',
    text: 'Refraction Test Type',
    url: '/setting/refractiontesttype',
  },
  {
    authority: 'settings.clinicsetting.tag',
    title: 'Clinic Setting',
    text: 'Tag',
    url: '/setting/tag',
  },
  {
    authority: 'settings.systemuser.systemuser',
    title: 'System User',
    text: 'User Profile',
    url: '/setting/userprofile',
  },
  {
    authority: 'settings.role',
    title: 'System User',
    text: 'User Group',
    url: '/setting/userrole',
  },
  //{
  //  title: 'Print Setup',
  //  text: 'Master Printout Setting',
  //  url: '/setting/masterprintoutsetting',
  //  authority: 'settings.printsetup.masterprintoutsetting',
  //},
  {
    authority: 'settings.printsetup.printoutsetting',
    title: 'Print Setup',
    text: 'Printout Setting',
    url: '/setting/printoutsetting',
  },
  {
    authority: 'settings.templates.smstemplate',
    title: 'Templates',
    text: 'SMS Template',
    url: '/setting/smstemplate',
  },
  {
    authority: 'settings.templates.documenttemplate',
    title: 'Templates',
    text: 'Document Template',
    url: '/setting/documenttemplate',
  },
  {
    authority: 'settings.templates.visitordertemplate',
    title: 'Templates',
    text: 'Visit Purpose',
    url: '/setting/visitordertemplate',
  },
  {
    authority: 'settings.clinicsetting.medicinetrivia',
    title: 'Templates',
    text: 'Medicine Trivia',
    url: '/setting/medicinetrivia',
  },
  // {
  //   title: 'Contact',
  //   text: 'Co-Payer',
  //   url: '/setting/company/1',
  // },
  {
    authority: 'settings.contact.supplier',
    title: 'Contact',
    text: 'Supplier',
    url: '/setting/company/2',
  },
  {
    authority: 'settings.contact.manufacturer',
    title: 'Contact',
    text: 'Manufacturer',
    url: '/setting/company/3',
  },
  {
    authority: 'settings.contact.referralsource',
    title: 'Contact',
    text: 'Referral Source',
    url: '/setting/referralsource',
  },
  {
    authority: 'settings.contact.referralperson',
    title: 'Contact',
    text: 'Referral Person',
    url: '/setting/referralperson',
  },
  {
    authority: 'settings.clinicsetting.package',
    title: 'Clinic Setting',
    text: 'Package',
    url: '/setting/package',
  },
  {
    authority: 'settings.clinicsetting.invoiceadjustment',
    title: 'Clinic Setting',
    text: 'Invoice Adjustment',
    url: '/setting/invoiceadjustment',
  },
  {
    authority: 'settings.clinicsetting.medicationingredient',
    title: 'Clinic Setting',
    text: 'Drug Ingredient',
    url: '/setting/medicationingredient',
  },
  {
    authority: 'settings.clinicsetting.drugallergy',
    title: 'Clinic Setting',
    text: 'Drug Allergy',
    url: '/setting/drugallergy',
  },
  {
    authority: 'settings.clinicsetting.medicationcontraindication',
    title: 'Clinic Setting',
    text: 'Medication Contraindication',
    url: '/setting/medicationcontraindication',
  },
  {
    authority: 'settings.clinicsetting.medicationinteraction',
    title: 'Clinic Setting',
    text: 'Medication Interaction',
    url: '/setting/medicationinteraction',
  },
  {
    authority: 'settings.clinicsetting.medicationsideeffect',
    title: 'Clinic Setting',
    text: 'Medication Side Effect',
    url: '/setting/medicationsideeffect',
  },
  {
    authority: 'settings.clinicsetting.genericmedication',
    title: 'Clinic Setting',
    text: 'Generic Drug',
    url: '/setting/genericmedication',
  },
  {
    authority: 'settings.clinicsetting.administrationroute',
    title: 'Clinic Setting',
    text: 'Route of Administration',
    url: '/setting/administrationroute',
  },
  {
    authority: 'settings.clinicsetting.checklist',
    title: 'Clinic Setting',
    text: 'Checklist',
    url: '/setting/checklist',
  },
  {
    authority: 'settings.clinicsetting.resource',
    title: 'Clinic Setting',
    text: 'Resource',
    url: '/setting/resource',
  },
  {
    authority: 'settings.clinicsetting.individualcomment',
    title: 'Templates',
    text: 'Individual Comment',
    url: '/setting/individualcomment',
    hiddenWhenClinicSettingIsOff: 'isEnableMedicalCheckupModule',
  },
  {
    authority: 'settings.clinicsetting.summarycomment',
    title: 'Templates',
    text: 'Summary Comment',
    url: '/setting/summarycomment',
    hiddenWhenClinicSettingIsOff: 'isEnableMedicalCheckupModule',
  },
  {
    authority: 'settings.clinicsetting.creditfacility',
    title: 'Clinic Setting',
    text: 'Credit Facility',
    url: '/setting/creditfacility',
  },
]
